palavra = input('Escreva sua variável: ')
print(palavra)
print('\33[36mEle é que tipo de valor?', type(palavra))
print('É um alfanumérico? ', palavra.isalnum())
print('É um alfa? ', palavra.isalpha())
print('É um padrão ascii? ', palavra.isascii())
print('É um decimal ? ', palavra.isdecimal())
print('É um digito? ', palavra.isdigit())
print('É uma variável válida? ', palavra.isidentifier())
print('É uma palavra minúscula ? ', palavra.islower())
print('É um numérico? ', palavra.isnumeric())
print('Tem espaço? ', palavra.isspace())
print('É imprimível ? ', palavra.isprintable())
print('É um título? ', palavra.istitle(), '\33[m')
# Conhecimento básico de formatação de str, nada complexo